// GIVE ALL CREDIT TO ELK
// MY DSC IS @2elk !!
    console.log('Site opened.')
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    console.log('Video Opened')
    location.reload()
